#!name=All-In-One-Search
#!desc=Safari全能搜索(需要把Safari的搜索引擎设置为：百度)
#!system=ios
#搬运自ATorNinja

[URL Rewrite]
# Safari全能搜索
# 以下为Safari全能搜索、需要把Safari的搜索引擎设置为：百度

#wk (Wikipedia中文)
^https:\/\/m\.baidu\.com/s\?from=.+&word=wk\+([^&]+) https://zh.wikipedia.org/wiki/$1 302

#wiki (Wikipedia)
^https:\/\/m\.baidu\.com/s\?from=.+&word=wiki\+([^&]+) https://wikipedia.org/wiki/$1 302

# yd  (有道词典)
^https:\/\/m\.baidu\.com/s\?from=.+&word=yd\+([^&]+) https://dict.youdao.com/search?q=$1 302

# trc  (Google 译至中)
^https:\/\/m\.baidu\.com/s\?from=.+&word=trc\+([^&]+) https://translate.google.com/#view=home&op=translate&sl=auto&tl=zh-CN&text=$1 302

# tre  (Google 译至英)
^https:\/\/m\.baidu\.com/s\?from=.+&word=tre\+([^&]+) https://translate.google.com/#view=home&op=translate&sl=auto&tl=en&text=$1 302

# trj  (Google 译至日)
^https:\/\/m\.baidu\.com/s\?from=.+&word=trj\+([^&]+) https://translate.google.com/#view=home&op=translate&sl=auto&tl=ja&text=$1 302

# gm (Google图片)
^https:\/\/m\.baidu\.com/s\?from=.+&word=gm\+([^&]+) https://www.google.com/search?&tbm=isch&q=$1 302

# gh (GitHub)
^https:\/\/m\.baidu\.com/s\?from=.+&word=gh\+([^&]+) https://github.com/search?q=$1 302

# tf (Google 搜索 TestFlight)
^https:\/\/m\.baidu\.com/s\?from=.+&word=tf\+([^&]+) https://www.google.com/search?as_q=$1&as_sitesearch=testflight.apple.com 302

# wb (微博)
^https:\/\/m\.baidu\.com/s\?from=.+&word=wb\+([^&]+) https://s.weibo.com/weibo/$1 302

# wx (微信)
^https:\/\/m\.baidu\.com/s\?from=.+&word=wx\+([^&]+) https://weixin.sogou.com/weixinwap?query=$1 302

# jd (京东)
^https:\/\/m\.baidu\.com/s\?from=.+&word=jd\+([^&]+) https://so.m.jd.com/ware/search.action?keyword=$1 302

# tb (淘宝)
^https:\/\/m\.baidu\.com/s\?from=.+&word=tb\+([^&]+) https://s.m.taobao.com/h5?q=$1 302

# tm (天猫)
^https:\/\/m\.baidu\.com/s\?from=.+&word=tm\+([^&]+) https://s.m.tmall.com/m/search.htm?q=$1 302

# ytb (YouTube)
^https:\/\/m\.baidu\.com/s\?from=.+&word=ytb\+([^&]+) https://www.youtube.com/results?search_query=$1 302

#vf（voflix视频网站）
^https:\/\/m\.baidu\.com/s\?from=.+&word=vf\+([^&]+) https://www.voflix.com/search/-------------.html?wd=$1 302

# ph (PornHub)
^https:\/\/m\.baidu\.com/s\?from=.+&word=ph\+([^&]+) https://cn.pornhub.com/video/search?search=$1 302

# bi (必应)
^https:\/\/m\.baidu\.com/s\?from=.+&word=bi\+([^&]+) https://cn.bing.com/search?q=$1 302

# bd (百度)
^https:\/\/m\.baidu\.com/s\?from=.+&word=bd\+([^&]+) https://www.baidu.com/s?wd=$1 302

# ccn (App Store 临时换至中国区)
^https:\/\/m\.baidu\.com/s\?from=.+&word=ccn https://itunes.apple.com/WebObjects/MZStore.woa/wa/resetAndRedirect?dsf=143465&mt=8&url=/WebObjects/MZStore.woa/wa/viewSoftware?mt=8&id=1108187390&cc=cn&urlDesc= 302

# uus (App Store 临时换至美国区)
^https:\/\/m\.baidu\.com/s\?from=.+&word=uus https://itunes.apple.com/WebObjects/MZStore.woa/wa/resetAndRedirect?dsf=143441&mt=8&url=/WebObjects/MZStore.woa/wa/viewSoftware?mt=8&id=1108187390&cc=us&urlDesc= 302

# jjp （APP Store 切换至JP）
^https:\/\/m\.baidu\.com/s\?from=.+&word=jjp https://itunes.apple.com/WebObjects/MZStore.woa/wa/resetAndRedirect?dsf=143462&mt=8&url=/WebObjects/MZStore.woa/wa/viewSoftware?mt=8&id=1108187390&cc=jp&urlDesc= 302

# ttr （APP Store 切换至TR）
^https:\/\/m\.baidu\.com/s\?from=.+&word=ttr https://itunes.apple.com/WebObjects/MZStore.woa/wa/resetAndRedirect?dsf=143480&mt=8&url=/WebObjects/MZStore.woa/wa/viewSoftware?mt=8&id=1108187390&cc=tr&urlDesc= 302

# ddg (DuckDuckGo)
^https:\/\/m\.baidu\.com/s\?from=.+&word=ddg\+([^&]+) https://duckduckgo.com/?ia=about&q=$1 302

# 无指令 (Google)
^https:\/\/m\.baidu\.com/s\?from=.+&word=([^&]+) https://www.google.com/search?q=$1 302

[MITM]
hostname = %APPEND% m.baidu.com
