#!name=QX重写转化&规则集解析
#!desc=使用方法在qx重写链接末尾加上qx 在surge模块链接末尾加sg 在规则集链接末尾加r_parser.list 支持QX & Clash规则集解析
#!author=@小白脸 @chengkongyiban
#!使用手册https://github.com/chengkongyiban/stash/tree/main/Rewrite_Parser_Wiki

[Script]

QX转换 = type=http-request,pattern=\/.+?\..+?qx$|qx\?(jsc|hnadd|hndel|n|y|x|del|i)=,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/chengkongyiban/stash/main/js/QX_Rewrite_Parser.js, timeout=60

#仅需要将Mock转为reject
Surge转换 = type=http-request,pattern=\/.+?\..+?sg$,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/chengkongyiban/shadowrocket/main/scripts/Surge_to_Shadowrocket.js, timeout=60

规则集转换 = type=http-request,pattern=r_parser.list$|r_parser.list\?.*,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/chengkongyiban/stash/main/js/rule_parser.js, timeout=60

#在QX脚本结尾加上 _script-converter-(stash|surge|loon|shadowrocket).js 根据你自己的app填写
脚本转换 = type=http-request,pattern=_script-converter-(stash|surge|loon|shadowrocket)\.js$,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/xream/scripts/main/surge/modules/script-converter/script-converter.js, timeout=60

[MITM]
hostname = %APPEND% github.com:443, raw.githubusercontent.com:443,gist.githubusercontent.com,gitlab.com
