#!name=文本预览器
#!desc=主要用于预览Safari浏览器无法直接预览，需要下载的文本，例如yaml snippet格式，在需要预览的链接末尾加.t_read.txt

[Script]

文本预览器 = type=http-request,pattern=\.t_read\.txt$,requires-body=1,max-size=3145728,script-path=https://github.com/chengkongyiban/shadowrocket/raw/main/scripts/txt_read.js,script-update-interval=0

[MITM]

hostname = %APPEND% github.com,raw.githubusercontent.com,gist.githubusercontent.com,gitlab.com
