#!name=学习网站
#!desc=认真学习
[URL Rewrite]
# > 10 PornHub[网页优化]@ddgksf2013 - 网站地址：https://cn.pornhub.com
^https:\/\/(cn|www)\.pornhub\.com\/_xa\/ads - reject-dict

[Script]
pornhub = type=http-response,requires-body=1,max-size=0,pattern=^https?:/\/(cn|www)\.pornhub\.com(\/?$|\/([?]|view|video).*$),script-path=https://raw.githubusercontent.com/chengkongyiban/shadowrocket/main/scripts/pornhub.js

[MITM]
hostname = %APPEND% *.pornhub.com
