name: Rule_Generate

on:
  schedule:
    - cron: '0 20 * * *'
  pull_request:
    branches: [ "main" ]
  repository_dispatch:
    types: [bot_trigger]
  workflow_dispatch:

# 🔥 消除 Node.js 20 警告
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print current directory
        run: |
          cd ./rule/
          pwd

      - name: "拉取"
        run: python rule/Script/Get_File.py

      - name: "合并"
        run: python rule/Script/Merge_File.py

      - name: Commit files
        run: |
          git config --local user.email "wwfnle@gmail.com"
          git config --local user.name "elnfnoosm"
          git add ./*
          git diff --quiet && git diff --staged --quiet || git commit -m "Update Rules"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: main
          force: false
